- !Packet
  name: TM_TRANSFER_FRAME

  fields:
    #
    # Start Transfer Frame Primary Header
    #####################################################################
    - !Field
      name: TransferFrameVersion
      type: MSB_U16
      mask: 0xA000
      bytes: [1, 2]

    - !Field
      name: SpacecraftId
      type: MSB_U16
      mask: 0x3F00
      bytes: [1, 2]

    - !Field
      name: MasterChannelId
      type: MSB_U16
      mask: 0xFF40
      bytes: [1, 2]

    - !Field
      name: VirtualChannelId
      type: MSB_U16
      mask: 0x00D0
      bytes: [1, 2]

    - !Field
      name: OCFflag
      type: MSB_U16
      mask: 0x0001
      bytes: [1, 2]

    - !Field
      name: MasterChannelFrameCount
      type: U8
      bytes: 3

    - !Field
      name: VirtualChannelFrameCount
      type: U8
      bytes: 4

    #
    # Start Transfer Frame Data Field Status
    #####################################################################
    - !Field
      name: TransferFrameSecondaryHeaderFlag
      type: MSB_U16
      mask: 0x8000
      bytes: [5, 6]

    - !Field
      name: SynchFlag
      type: MSB_U16
      mask: 0x4000
      bytes: [5, 6]

    - !Field
      name: PacketOrderFlag
      type: MSB_U16
      mask: 0x2000
      bytes: [5, 6]

    - !Field
      name: SegmentLengthId
      type: MSB_U16
      mask: 0x1800
      bytes: [5, 6]

    - !Field
      name: FirstHeaderPointer
      type: MSB_U16
      mask: 0x03FF
      bytes: [5, 6]

    #
    # Start Transfer Frame Secondary Header
    #
    # The Transfer Frame Secondary Header shall be of fixed length within
    # the associated Master or Virtual Channel throughout a Mission
    # Phase. Adjust the fields here as needed to meet the expected
    # length.
    #####################################################################
    #- !Field
      #name: SecondaryHeaderVersionNumber
      #type: U8
      #mask: 0xC0

    #- !Field
      #name: SecondaryHeaderLength
      #type: U8
      #mask: 0x4F
      #bytes: <insert here>

    # Secondary Header Data Field can contain up to 63 Octets. Repeat as
    # needed and update names to meet size requirements.
    #- !Field
      #name: SHDF1
      #type: U8
      #bytes: <insert here>

    #- !Field
      #name: SHDF2
      #type: MSB_U16
      #bytes: <insert here>

    #- !Field
      #name: SHDF3
      #type: MSB_U32
      #bytes: <insert here>

    #
    # Start Packet Section
    #####################################################################
    - !Field
      name:       version
      desc:       Indicates CCSDS Version-1 (does not change)
      #bytes:       0
      bytes: 7
      type:       U8
      mask:       0xE0
    - !Field
      name:       type
      desc:       |
        Distinguishes between core and payload packet types to extend the
        APID space to 4032
      #bytes:       0
      bytes: 7
      type:       U8
      mask:       0x10
      enum:
        0: 'Core'
        1: 'Payload'
    - !Field
      name:       secondary_header_flag
      desc:       |
        Indicates whether, or not, a Secondary Header follows the primary
        header.
      #bytes:       0
      bytes: 7
      type:       U8
      mask:       0x08
      enum:
        0: 'Not Present'
        1: 'Present'
    - !Field
      name:       apid
      desc:       |
        Used in conjunction with Type to define the Logical Data Path
      bytes:       [8, 9]
      type:       MSB_U16
      mask:       0x07FF
    - !Field
      name:       sequence_flags
      desc:      |
        When sending commands, the sequence flags must be marked as
        unsegmented data. All other PL packets may be per source/destination
        ICDs.
      bytes:       10
      type:       U8
      mask:       0xC0
      enum:
        0: 'Continuation Segment'
        1: 'First Segment'
        2: 'Last Segment'
        3: 'Unsegmented'
    - !Field
      name: sequence_count
      desc:      |
        Sequential count which numbers each packet on a Logical Data Path,
        i.e. a separate counter is maintained for each source-destination
        pair.
      bytes: [10, 11]
      mask: 0x3FFF
      type: MSB_U16
    - !Field
      name: packet_length
      desc:      |
        Sequential count which expresses the length of the remainder of the
        packet including checkword if present. The value is the number of
        bytes (octets) following the field minus 1.
      bytes: [12, 13]
      type: MSB_U16

    # Include packet secondary header info as necessary here.
    #
    # Hardcoding the length of the Data Field here. We're expecting to receive
    # 1514 octet length dat fields.
    - !include data_field_defn.yaml
